Repository TechnionYP5779/Testock, pull requests merged in 2018-12, with the labels that each got.

#9 #5 Added service for images extraction from PDF
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/pdf.service.spec.ts
  src/app/pdf.service.ts
Labels: Feature

#29 Issue/image upload name uniquness
  src/app/core/db.service.ts
  src/app/core/upload.service.ts
Labels: bug

#32 Issue/solution grade is uploaded as string
  src/app/core/db.service.ts
  src/app/core/entities/course.ts
  src/app/core/entities/exam.ts
  src/app/core/entities/question.ts
  src/app/core/entities/solution.ts
  src/app/core/upload.service.ts
  src/app/ui/upload/upload.component.ts
Labels: bug

#40 Feature: download a PDF consists of best solutions for each question of an exam
  src/app/ui/exam/exam.component.html
Labels: Feature, Firebase

#57 Bug/pdfjs worker not found
  src/app/core/pdf.service.ts
  src/index.html
Labels: bug

#49 Issue/design courses page
  src/app/ui/courses/courses.component.html
  src/app/ui/header/header.component.html
Labels: Front End

#63 Issue/support solution with multiple images
  src/app/core/entities/solution.ts
  src/app/core/upload.service.ts
  src/app/ui/upload/upload.component.ts
Labels: Back End

#56 Issue/drag and drop
  src/app/ui/upload/upload.component.css
  src/app/ui/upload/upload.component.html
  src/app/ui/upload/upload.component.ts
Labels: Front End

#46 Issue/home page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/ui/home/home.component.html
  src/app/ui/home/home.component.scss
  src/app/ui/home/home.component.spec.ts
  src/app/ui/home/home.component.ts
  src/assets/images/homepage/cs-dog.jpg
  src/assets/images/homepage/cs-lecture.jpg
  src/assets/images/homepage/cs-technion.jpg
Labels: Front End

#78 Upload page refactor
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/core/core.module.ts
  src/app/core/safe-url.pipe.spec.ts
  src/app/core/safe-url.pipe.ts
  src/app/core/upload.service.ts
  src/app/ui/upload/scan-page/scan-page.component.html
  src/app/ui/upload/scan-page/scan-page.component.scss
  src/app/ui/upload/scan-page/scan-page.component.spec.ts
  src/app/ui/upload/scan-page/scan-page.component.ts
  src/app/ui/upload/upload-question/upload-question.component.html
  src/app/ui/upload/upload-question/upload-question.component.scss
  src/app/ui/upload/upload-question/upload-question.component.spec.ts
  src/app/ui/upload/upload-question/upload-question.component.ts
  src/app/ui/upload/upload.component.html
  src/app/ui/upload/upload.component.scss
  src/app/ui/upload/upload.component.ts
  src/assets/styles/mixins.scss
  src/styles.scss
Labels: Angular, Front End

#79 Bug/facebook profile image is blurred
  src/app/app.module.ts
  src/app/core/auth.service.ts
  src/app/users/facebook-profile-picture/facebook-profile-picture.component.html
  src/app/users/facebook-profile-picture/facebook-profile-picture.component.scss
  src/app/users/facebook-profile-picture/facebook-profile-picture.component.spec.ts
  src/app/users/facebook-profile-picture/facebook-profile-picture.component.ts
  src/app/users/user-profile/user-profile.component.html
  src/app/users/user-profile/user-profile.component.ts
Labels: bug

#117 Issue/course name link
  src/app/ui/courses/courses.component.html
Labels: Front End
