Repository TechnionYP5779/Testock, pull requests merged in 2019-01, with the labels that each got.

#128 added form reset when upload is done
  src/app/ui/upload/upload.component.html
  src/app/ui/upload/upload.component.ts
Labels: Front End, enhancement

#129 added option to remove first page, even pages and odd pages
  src/app/ui/upload/upload.component.html
  src/app/ui/upload/upload.component.ts
Labels: Feature

#149 Bug/course component access of undefined
  src/app/ui/course/course.component.html
Labels: bug

#150 Feature/roles
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/core/admin-only.guard.spec.ts
  src/app/core/admin-only.guard.ts
  src/app/core/auth.service.ts
  src/app/core/db.service.ts
  src/app/core/entities/faculty.ts
  src/app/core/entities/user.ts
  src/app/core/users-only.guard.spec.ts
  src/app/core/users-only.guard.ts
  src/app/ui/admin/admin.component.html
  src/app/ui/admin/admin.component.scss
  src/app/ui/admin/admin.component.spec.ts
  src/app/ui/admin/admin.component.ts
  src/app/ui/admin/faculty/faculty.component.html
  src/app/ui/admin/faculty/faculty.component.scss
  src/app/ui/admin/faculty/faculty.component.spec.ts
  src/app/ui/admin/faculty/faculty.component.ts
  src/app/ui/course/course.component.html
  src/app/ui/course/course.component.ts
  src/app/ui/courses/courses.component.html
  src/app/ui/exam/exam.component.html
  src/app/ui/exam/exam.component.ts
  src/app/ui/header/header.component.html
  src/app/ui/header/header.component.ts
  src/app/ui/question/question.component.html
  src/app/ui/question/question.component.ts
  src/app/ui/solution/solution.component.html
  src/app/ui/solution/solution.component.scss
  src/app/ui/solution/solution.component.ts
Labels: Feature

#153 Feature/discussions/db support
  src/app/core/db.service.ts
  src/app/core/entities/comment.ts
  src/app/core/entities/topic.ts
Labels: Feature

#159 fixes #154
  src/app/core/entities/comment.ts
Labels: bug

#164 Bug/topic comment missing timestamp
  src/app/core/db.service.ts
  src/app/core/entities/comment.ts
  src/app/core/entities/topic.ts
Labels: bug

#160 Bug/solution photos not removed
  src/app/core/db.service.ts
  src/app/ui/solution/solution.component.ts
Labels: bug

#166 fixes #163
  src/app/core/db.service.ts
Labels: bug

#167 Feature/discussions/ask question
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/ui/course/course.component.html
  src/app/ui/create-topic/create-topic.component.html
  src/app/ui/create-topic/create-topic.component.scss
  src/app/ui/create-topic/create-topic.component.spec.ts
  src/app/ui/create-topic/create-topic.component.ts
  src/index.html
Labels: Feature, enhancement

#169 Feature/course topic
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/core/db.service.ts
  src/app/core/entities/comment.ts
  src/app/core/entities/topic.ts
  src/app/ui/comment/comment.component.html
  src/app/ui/comment/comment.component.scss
  src/app/ui/comment/comment.component.spec.ts
  src/app/ui/comment/comment.component.ts
  src/app/ui/topic/topic.component.html
  src/app/ui/topic/topic.component.scss
  src/app/ui/topic/topic.component.spec.ts
  src/app/ui/topic/topic.component.ts
  src/app/users/facebook-profile-picture/facebook-profile-picture.component.ts
Labels: Feature

#170 Feature/add comment
  src/app/app.module.ts
  src/app/core/db.service.ts
  src/app/ui/create-comment/create-comment.component.html
  src/app/ui/create-comment/create-comment.component.scss
  src/app/ui/create-comment/create-comment.component.spec.ts
  src/app/ui/create-comment/create-comment.component.ts
  src/app/ui/topic/topic.component.html
Labels: Feature

#177 Feature/discussions for questions
  src/app/core/db.service.ts
  src/app/ui/question/question.component.html
  src/app/ui/question/question.component.ts
Labels: Feature

#182 Feature/chrome plugin
  src/app/app-routing.module.ts
  src/app/chrome-plugin/course.js
  src/app/chrome-plugin/images/testock128.png
  src/app/chrome-plugin/images/testock16.png
  src/app/chrome-plugin/images/testock32.png
  src/app/chrome-plugin/images/testock48.png
  src/app/chrome-plugin/manifest.json
  src/app/chrome-plugin/popup.html
  src/app/chrome-plugin/popup.js
  src/app/chrome-plugin/scan.js
  src/app/ui/upload/upload.component.ts
Labels: Chrome plug-in
